### ISSUE TITLE
Add smooth Hamburger menu for responsive design to the navbar

### ISSUE THREAD

**Issue by fykaa** [TechOS-Bell/techOS-Bell#17]
![image](https://user-images.githubusercontent.com/97490463/194856179-9d9135e8-c1fe-4b15-adab-ff58013309da.png)

Take help from - https://themewagon.com/responsive-navbar-collection/

Must have in the PR - 
1) Smooth Responsiveness for hamburger menu opening closing
2) Responsive (add a Hamburger Menu for Mobile devices)
3) Click anywhere to close the menu feature

Rules -

1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by Adityageek** [comment]
Hi @fykaa Can you please assigne this to me.

**Comment by fykaa** [comment]
@Adityageek updates?

**Comment by Adityageek** [comment]
Yes @fykaa  I am working on this will raise the PR today.

**Comment by Adityageek** [comment]
Hi @fykaa In this hamburger menu if I'm trying to apply Bootstrap hamburger the existing design will be change. So is it fine with you? 
Thanks!

**Comment by fykaa** [comment]
I hope it doesn't make Extreme Changes to the Complete design. 
Other than that, Adding Bootstrap is fine :)
