### ISSUE TITLE
Improve About Section UI

### ISSUE THREAD

**Issue by fykaa** [TechOS-Bell/techOS-Bell#3]
Apply creative and professional Ideas to this About section | Take Ideas from the Internet 
![image](https://user-images.githubusercontent.com/97490463/194847040-59f36a9e-58d4-45dc-b745-4f556256e024.png)

Samples (add random text) - 
![image](https://user-images.githubusercontent.com/97490463/194855036-30a1890f-bee2-4fed-84f5-087c5924b679.png)
![image](https://user-images.githubusercontent.com/97490463/194855128-6d24bac5-fd55-4e84-9b8e-6264b9819d96.png)
![image](https://user-images.githubusercontent.com/97490463/194855241-ab580c06-dad2-453f-9286-8624da8d58d2.png)

Rules -
1) Comment below to Get Assigned
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by Divyesh1511** [comment]
Do this about page need to be coded or just need the creative new UI for the page?

**Comment by fykaa** [comment]
coded

**Comment by shrutilenka** [comment]
Hey, @fykaa I am interested to work on the project. Could you please assign me this issue?

**Comment by MahfuzRP** [comment]
Hi, Please assign me this issues.

**Comment by fykaa** [comment]
@shrutilenka You are assigned, Please follow up the [instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)

**Comment by anushkamandal25** [comment]
Hello! I would like to contribute on this issue. Please assign me

**Comment by fykaa** [comment]
sure @anushkamandal25
