### ISSUE TITLE
Create a Custom Attractive Scroll Bar with Gradient colors

### ISSUE THREAD

**Issue by fykaa** [TechOS-Bell/techOS-Bell#47]
Update to a creative Scroll Bar for the Site's homepage - 

Take Reference/Examples from - 
https://onaircode.com/html-css-custom-scrollbar-examples/

Must in The PR:
- Attractive Scrollbar design
- Gradient and creative features
- Properly Functioning

Rules -
1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format
5) Most efficient contributions gets automatically listed [here](https://github.com/TechOS-Bell/techOS-Bell#-contributors-of-the-month-based-on-most-efficient-contributions-)

PRs Lacking the MUSTS and RULES mentioned above will be ignored.

**Comment by Suveksha25** [comment]
I would like to work on this. Can you assign it to me

**Comment by fykaa** [comment]
Please follow these Musts and Rules in your PR #48

**Comment by Adityageek** [comment]
Hi @fykaa can you please assign this to me.

**Comment by fykaa** [comment]
@Adityageek Done
